version: '3'

services:
  db:
    image: postgres:12
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    ports:
      - 5432:5432
  api:
    build:
      context: ./proctoring
      args:
        DATABASE_URL: postgres://postgres:postgres@db:5432/proctoring
        SECRET_KEY_BASE: SECRET_KEY_BASE # must be replaced
    env_file:
      - .env
    ports:
      - 5000:5000
    depends_on:
      - db
  ui:
    build: ./proctoring-ui
    ports:
      - 8080:80
    depends_on:
      - api

volumes:
  db-data: